---
version: "3"

networks:
  traefik-network:
    external: true

volumes:
  adguard-data:
    name: adguard-data

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    environment:
      - TZ="Asia/Krasnoyarsk"
    expose:
      - "80"
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.adguard.entrypoints=https
      - traefik.http.routers.adguard.rule=Host("adguard.bwonsamdi.ru") || Host("dns.bwonsamdi.ru")
      - traefik.http.routers.adguard.middlewares=adminList@file,default@file
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.tls.certresolver=letsencrypt
      - traefik.http.routers.adguard.tls.options=modern@file
      - traefik.http.services.adguard.loadbalancer.server.port=80

#      - traefik.tcp.routers.adguard-tls.rule=HostSNI("adguard.bwonsamdi.ru")
#      - traefik.tcp.routers.adguard-tls.tls=true
#      - traefik.tcp.routers.adguard-tls.entrypoints=dot
#      - traefik.tcp.routers.adguard-tls.tls.certresolver=letsencrypt
#      - traefik.tcp.services.adguard-tls.loadbalancer.server.port=53

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - adguard-data:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf
