---
version: "3"

networks:
  traefik-network:
    external: true

volumes:
  wgConfigs:
    name: wgConfigs

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Asia/Krasnoyarks
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=home,notebook,nothing,sweety
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wgConfigs:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  wgNginx:
    image: nginx
    container_name: wgNginx
    environment:
      - TZ=Asia/Krasnoyarks
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.wgNginx.entrypoints=https
      - traefik.http.routers.wgNginx.rule=Host("wg.bwonsamdi.ru")
      - traefik.http.routers.wgNginx.middlewares=srcAllowedList@file,default@file
      - traefik.http.routers.wgNginx.tls=true
      - traefik.http.routers.wgNginx.tls.certresolver=letsencrypt
      - traefik.http.routers.wgNginx.tls.options=modern@file
      - traefik.http.services.wgNginx.loadbalancer.server.port=80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wgConfigs:/usr/share/nginx/html:ro
