name: VPS docker composer 

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y rsync
      - run: sudo mkdir -p $HOME/.ssh && sudo echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/id_rsa"
      - run: sudo chmod 600 "$HOME/.ssh/id_rsa"
      - run: rsync -e "ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete ./configs/traefik/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER }}:/opt/traefik/configs
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER }} "chown -R ${{ secrets.VPS_USER }}:docker /opt/traefik"
      - run: docker context create ssh-box --docker "host=ssh://${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER }}"
      - run: docker --context ssh-box compose -f ./traefik.yml -p traefik up -d
