name: VPS docker composer 

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y rsync ssh
      - run: mkdir -p $HOME/.ssh
      - run: echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
      - run: echo "Host *" > $HOME/.ssh/config && echo " StrictHostKeyChecking no" >> $HOME/.ssh/config && echo " UserKnownHostsFile /dev/null" >> $HOME/.ssh/config
      - run: sudo chmod 400 $HOME/.ssh/*
      - run: sudo service ssh restart
      - run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER }} "chown -R ${{ secrets.VPS_USER }}:docker /opt/traefik"
      - run: rsync --archive --compress --delete ./configs/traefik/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER }}:/opt/traefik/configs
      - run: docker context create ssh-box --docker "host=ssh://${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER }}"
      - run: docker --context ssh-box compose -f ./traefik.yml -p traefik up -d
